////////////////////////////////////////////////////////////////////
// Spawn Tamoko outside the Iron Throne if Chapter 7 starts there //
////////////////////////////////////////////////////////////////////

IF
	Global("TamokoMove","GLOBAL",0)
	Global("#LF_AltCh6","GLOBAL",1)
	Global("Chapter","GLOBAL",7)
	!Exists("Tamoko")  // Tamoko
	!Dead("Sarevok")  // Sarevok
	!Dead("Sarevok")  // Sarevok
	!Dead("Tamoko")  // Tamoko
THEN
	RESPONSE #100
		CreateCreature("TAMOKO",[440.805],N)
END