//////////////////////////////
// 3rd floor of Library     // 
// Get rid of the merchants //
//////////////////////////////

IF
	OnCreation()
	Global("Chapter","GLOBAL",5)
	Global("#L_FCleared","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("#L_FCleared","MYAREA",1)
		ActionOverride("Bruno",DestroySelf())
		ActionOverride("Kestor",DestroySelf())
		ActionOverride("Rieltar",DestroySelf())
		ActionOverride("Tuth",DestroySelf())
END

