///////////////////////////////////////////
// Get rid of Sarevok from the 2nd floor //
///////////////////////////////////////////

IF
	OnCreation()
	Global("Chapter","GLOBAL",5)
	Global("#L_FCleared","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("#L_FCleared","MYAREA",1)
		ActionOverride("Koveras",DestroySelf())
		ActionOverride("BENDAL",DestroySelf())
		ActionOverride("CHANTE2",DestroySelf())
END
