//////////////////////////////////////////
// Priest Quarters                      // 
// Get rid of the doppleganger and cats //
//////////////////////////////////////////

IF
	OnCreation()
	Global("Chapter","GLOBAL",5)
	Global("#L_FCleared","MYAREA",0)
THEN
	RESPONSE #100
		SetGlobal("#L_FCleared","MYAREA",1)
		ActionOverride("POGHM9",DestroySelf())
		ActionOverride("CAT",DestroySelf())
		ActionOverride("CATDEAD",DestroySelf())
END

