/////////////////////////////////////////////////////
// Swaps out diary before or after Sarevok is dead //
// In case Transitions is loaded                   //
/////////////////////////////////////////////////////

IF
	Exists("Cythan")
	Global("Chapter","GLOBAL",7)
	Global("#LF_AltCh6","GLOBAL",1)
	Global("#L_DiarySet","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("#L_DiarySet","GLOBAL",1)
		ActionOverride("Cythan",DestroyItem("SCRL3F"))
		GiveItemCreate("#LSCRL3F","Cythan",1,0,0)
END